source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ZingleSDK_Example' do
  pod 'ZingleSDK', :path => '../'
end

target 'Tests' do
  pod 'ZingleSDK', :path => '../'
end

# Cocoapods 1.3.1 is setting all library Swift versions to 3.2 for some asinine reason.  I love you, Cocoapods.
# The cause should really be investigated and this post_install script removed.
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '4.0'
		end
	end
end
