source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'ZingleSDK_Example' do
  pod 'ZingleSDK', :path => '../'
  pod 'JSQMessagesViewController', :path => 'JSQMessagesViewController'
  
	# We don't actually use SBObjectiveCWrapper; our SDK dependency does, but that project isn't actually being
	#  pushed to the pod trunk.  We need to manually point the subdependency at Github.
	pod 'SBObjectiveCWrapper', :git => 'https://github.com/SwiftyBeaver/SBObjectiveCWrapper.git'
end

target 'Tests' do
  pod 'ZingleSDK', :path => '../'
  pod 'JSQMessagesViewController', :path => 'JSQMessagesViewController'
  
	# We don't actually use SBObjectiveCWrapper; our SDK dependency does, but that project isn't actually being
	#  pushed to the pod trunk.  We need to manually point the subdependency at Github.
	pod 'SBObjectiveCWrapper', :git => 'https://github.com/SwiftyBeaver/SBObjectiveCWrapper.git'
end

post_install do |installer|
	# Pods that have not yet fixed implicit self retain warnings
	shamefulImplicitSelfPods = ['Analytics', 'CocoaLumberjack', 'JVFloatLabeledTextField', 'MGSwipeTableCell', 'WootricSDK']
	
	# Pods that have empty block parameter list prototype warnings
	shamefulBlockPrototypePods = ['Mantle']

	installer.pods_project.targets.each do |target|
      if shamefulImplicitSelfPods.include? target.name
         target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = false
         end
      end
		
      if shamefulBlockPrototypePods.include? target.name
         target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = false
         end
      end

      target.build_configurations.each do |config|
         config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      end
	end
end
